/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Researcher } from "./Researcher";
import { ResearcherCountArgs } from "./ResearcherCountArgs";
import { ResearcherFindManyArgs } from "./ResearcherFindManyArgs";
import { ResearcherFindUniqueArgs } from "./ResearcherFindUniqueArgs";
import { DeleteResearcherArgs } from "./DeleteResearcherArgs";
import { ResearcherService } from "../researcher.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Researcher)
export class ResearcherResolverBase {
  constructor(
    protected readonly service: ResearcherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Researcher",
    action: "read",
    possession: "any",
  })
  async _researchersMeta(
    @graphql.Args() args: ResearcherCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Researcher])
  @nestAccessControl.UseRoles({
    resource: "Researcher",
    action: "read",
    possession: "any",
  })
  async researchers(
    @graphql.Args() args: ResearcherFindManyArgs
  ): Promise<Researcher[]> {
    return this.service.researchers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Researcher, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Researcher",
    action: "read",
    possession: "own",
  })
  async researcher(
    @graphql.Args() args: ResearcherFindUniqueArgs
  ): Promise<Researcher | null> {
    const result = await this.service.researcher(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Researcher)
  @nestAccessControl.UseRoles({
    resource: "Researcher",
    action: "delete",
    possession: "any",
  })
  async deleteResearcher(
    @graphql.Args() args: DeleteResearcherArgs
  ): Promise<Researcher | null> {
    try {
      return await this.service.deleteResearcher(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
