/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Cryptocurrency } from "./Cryptocurrency";
import { CryptocurrencyCountArgs } from "./CryptocurrencyCountArgs";
import { CryptocurrencyFindManyArgs } from "./CryptocurrencyFindManyArgs";
import { CryptocurrencyFindUniqueArgs } from "./CryptocurrencyFindUniqueArgs";
import { DeleteCryptocurrencyArgs } from "./DeleteCryptocurrencyArgs";
import { CryptocurrencyService } from "../cryptocurrency.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Cryptocurrency)
export class CryptocurrencyResolverBase {
  constructor(
    protected readonly service: CryptocurrencyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "read",
    possession: "any",
  })
  async _cryptocurrenciesMeta(
    @graphql.Args() args: CryptocurrencyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Cryptocurrency])
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "read",
    possession: "any",
  })
  async cryptocurrencies(
    @graphql.Args() args: CryptocurrencyFindManyArgs
  ): Promise<Cryptocurrency[]> {
    return this.service.cryptocurrencies(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Cryptocurrency, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "read",
    possession: "own",
  })
  async cryptocurrency(
    @graphql.Args() args: CryptocurrencyFindUniqueArgs
  ): Promise<Cryptocurrency | null> {
    const result = await this.service.cryptocurrency(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Cryptocurrency)
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "delete",
    possession: "any",
  })
  async deleteCryptocurrency(
    @graphql.Args() args: DeleteCryptocurrencyArgs
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.deleteCryptocurrency(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
