/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CryptocurrencyService } from "../cryptocurrency.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CryptocurrencyCreateInput } from "./CryptocurrencyCreateInput";
import { Cryptocurrency } from "./Cryptocurrency";
import { CryptocurrencyFindManyArgs } from "./CryptocurrencyFindManyArgs";
import { CryptocurrencyWhereUniqueInput } from "./CryptocurrencyWhereUniqueInput";
import { CryptocurrencyUpdateInput } from "./CryptocurrencyUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CryptocurrencyControllerBase {
  constructor(
    protected readonly service: CryptocurrencyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cryptocurrency })
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCryptocurrency(
    @common.Body() data: CryptocurrencyCreateInput
  ): Promise<Cryptocurrency> {
    return await this.service.createCryptocurrency({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Cryptocurrency] })
  @ApiNestedQuery(CryptocurrencyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cryptocurrencies(
    @common.Req() request: Request
  ): Promise<Cryptocurrency[]> {
    const args = plainToClass(CryptocurrencyFindManyArgs, request.query);
    return this.service.cryptocurrencies({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Cryptocurrency | null> {
    const result = await this.service.cryptocurrency({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() data: CryptocurrencyUpdateInput
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.updateCryptocurrency({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Cryptocurrency",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.deleteCryptocurrency({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
